### ISSUE TITLE
pip install discord 

### ISSUE THREAD

**Issue by BenGamra20** [swagkarna/Spotify-Account-Creator-Bot#2]
C:\Python27>pip install discord
Collecting discord
  Using cached https://files.pythonhosted.org/packages/a3/0b/5d042064a1b1efa99bbe1c98458d35fdca6dcbef4e5c7700ec01bc3b0794/discord-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\sbs\appdata\local\temp\pip-build-lyeaoe\discord\setup.py", line 5, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\sbs\appdata\local\temp\pip-build-lyeaoe\discord\
You are using pip version 9.0.1, however version 20.2.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Any solution please i'm new to python and still  get this error

**Comment by Oberonskii** [comment]
Type python -m pip install --upgrade pip
